---
title: "Revenue Indicator Analysis"
author: "Don Boyd"
date: "`r format(Sys.time(), '%B %d, %Y')`"
output:
  html_notebook:
    df_print: paged
    toc: yes
    toc_depth: 5
always_allow_html: yes    
    
editor_options: 
  chunk_output_type: console
---

<!-- comments -->
<!-- -->


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo=FALSE, warning=FALSE, message=FALSE)
```


```{r system_specific_values, include=FALSE}

```


```{r globals, include=FALSE}

```


```{r libraries, include=FALSE}
library("magrittr")
library("plyr") # needed for ldply; must be loaded BEFORE dplyr
library("tidyverse")
options(tibble.print_max = 60, tibble.print_min = 60) # if more than 60 rows, print 60 - enough for states
# ggplot2 tibble tidyr readr purrr dplyr stringr forcats

library("scales")
library("hms") # hms, for times
library("lubridate") # lubridate, for date/times
library("vctrs")

library("grDevices")
library("knitr")
library("kableExtra")

# library("btools")

library("DT") # for datatable

library("zoo") # for rollapply

library("broom") # for automating the cleanup of complex output
library("tsoutliers")

library("janitor")

```
